import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './UI/Navbar/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sinp-Templete',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="{inter.className} max-w-screen-2xl bg-white mx-auto px-4 md:px-10 2xl:px-24 py-6 lg:py-0"><Navbar/>{children}</body>
    </html>
  )
}
