import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";

import "./globals.css";
import Navbar from "./Navbar/page";
import Footer from "./Components/footer";


const inter = Inter({ subsets: ["latin"], weight: "400" });
const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Sinp-Templete",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="{inter.className} {poppins.className} max-w-screen-2xl bg-white mx-auto font-poppins text-dark text-sm leading-loose">
        {/* <Navbar/> */}
        <Navbar/>
        {children}


        {/* <Footer/>*/}
        <Footer/>
      </body>
    </html>
  );
}
